CREATE TABLE tac01_usuario (id_usuario int4 NOT NULL, tx_nickname int4 NOT NULL, tx_correo_inicio int4 NOT NULL, tx_password int4 NOT NULL, fh_creacion timestamp NOT NULL, fh_ultimo_acceso timestamp, nu_intentos_err int4 NOT NULL, PRIMARY KEY (id_usuario));
CREATE TABLE tci01_paciente (id_paciente SERIAL NOT NULL, fk_id_persona int4 NOT NULL, tx_matriculación int4 NOT NULL, fh_afiliacion timestamp NOT NULL, PRIMARY KEY (id_paciente));
CREATE TABLE tci02_estado_cita (id_estado SERIAL NOT NULL, tx_nombre varchar(100) NOT NULL, PRIMARY KEY (id_estado));
CREATE TABLE tci03_cita (id_cita SERIAL NOT NULL, fk_id_hospital int4 NOT NULL, fk_id_personal int4 NOT NULL, fk_id_paciente int4 NOT NULL, fk_id_estado int4 NOT NULL, fh_cita timestamp NOT NULL, PRIMARY KEY (id_cita));
CREATE TABLE tor01_puestos (id_puesto SERIAL NOT NULL, tx_nombre text NOT NULL, tx_descripcion text NOT NULL, nu_jerarquia int4 NOT NULL, st_activo bool NOT NULL, PRIMARY KEY (id_puesto));
COMMENT ON COLUMN tor01_puestos.nu_jerarquia IS 'Este campo debera utilizarse para representar la importancia del puesto siendo desde 0 el mas importante hasta n, el menos importante, por default 0.';
CREATE TABLE tor02_unidades (id_unidad SERIAL NOT NULL, tx_nombre varchar(5000) NOT NULL, fk_id_unidad_padre int4, tx_descripcion text NOT NULL, nu_capacidad int4 NOT NULL, st_habilitada int4 NOT NULL, PRIMARY KEY (id_unidad));
CREATE TABLE tor03_personal (id_personal SERIAL NOT NULL, fk_id_persona int4 NOT NULL, fk_id_puesto int4 NOT NULL, fk_id_area int4 NOT NULL, tx_titulo text NOT NULL, PRIMARY KEY (id_personal));
CREATE TABLE tor04_areas (id_area SERIAL NOT NULL, tx_nombre varchar(100) NOT NULL, fk_id_area int4, fk_id_unidad int4 NOT NULL, st_activa bool NOT NULL, PRIMARY KEY (id_area));
CREATE TABLE tpe01_persona (id_persona SERIAL NOT NULL, tx_nombre varchar(250) NOT NULL, tx_primer_apellido varchar(250) NOT NULL, tx_segundo_apellido varchar(250), tx_identificador_persona text, fh_nacimiento date, st_paciente bool NOT NULL, PRIMARY KEY (id_persona));
CREATE TABLE tpe02_contacto (id_contacto SERIAL NOT NULL, fk_id_persona int4 NOT NULL, tx_telefono varchar(10), tx_celular varchar(10), tx_correo text, PRIMARY KEY (id_contacto));
CREATE TABLE tpe03_domicilio (id_domicilio SERIAL NOT NULL, fk_id_persona int4 NOT NULL, tx_calle text NOT NULL, tx_exterior text NOT NULL, tx_interior text, tx_municipio text NOT NULL, tx_entidad text NOT NULL, tx_asentamiento text NOT NULL, tx_referencias text, PRIMARY KEY (id_domicilio));
ALTER TABLE tac01_usuario ADD CONSTRAINT FKtac01_usua729142 FOREIGN KEY (id_usuario) REFERENCES tpe01_persona (id_persona);
ALTER TABLE tci01_paciente ADD CONSTRAINT FKtci01_paci689240 FOREIGN KEY (fk_id_persona) REFERENCES tpe01_persona (id_persona);
ALTER TABLE tci03_cita ADD CONSTRAINT FKtci03_cita198256 FOREIGN KEY (fk_id_paciente) REFERENCES tci01_paciente (id_paciente);
ALTER TABLE tci03_cita ADD CONSTRAINT FKtci03_cita407258 FOREIGN KEY (fk_id_estado) REFERENCES tci02_estado_cita (id_estado);
ALTER TABLE tor03_personal ADD CONSTRAINT FKtor03_pers177900 FOREIGN KEY (fk_id_persona) REFERENCES tpe01_persona (id_persona);
ALTER TABLE tor03_personal ADD CONSTRAINT FKtor03_pers971994 FOREIGN KEY (fk_id_area) REFERENCES tor04_areas (id_area);
ALTER TABLE tor04_areas ADD CONSTRAINT FKtor04_area205023 FOREIGN KEY (fk_id_unidad) REFERENCES tor02_unidades (id_unidad);
ALTER TABLE tor03_personal ADD CONSTRAINT FKtor03_pers52107 FOREIGN KEY (fk_id_puesto) REFERENCES tor01_puestos (id_puesto);
ALTER TABLE tpe03_domicilio ADD CONSTRAINT FKtpe03_domi951702 FOREIGN KEY (fk_id_persona) REFERENCES tpe01_persona (id_persona);
ALTER TABLE tpe02_contacto ADD CONSTRAINT FKtpe02_cont405527 FOREIGN KEY (fk_id_persona) REFERENCES tpe01_persona (id_persona);
